import type { RushLevel } from './logic';

/**
 * 주차장 50 — 무작위로 차를 놓은 배치에서 갈 수 있는 모든 배치를 넓히고, 다 푼 배치에서 거꾸로 가장 먼 배치를 출발 판으로 (우리 풀이기로 새로 만든 판).
 * par = 가장 적은 수(앞으로 다시 풀어 확인). 동네 12 · 시장 14 · 놀이공원 13 · 도심 11.
 */
export const LEVELS: RushLevel[] = [
  { world: 'easy', par: 2, rows: ['..BBDD', '....E.', 'AA..E.', '......', '.C....', '.C....'] },
  { world: 'easy', par: 3, rows: ['.E.BB.', '.E..F.', '.EAAF.', 'D..CC.', 'D.....', 'D.....'] },
  { world: 'easy', par: 3, rows: ['......', '....BC', 'AA..BC', '.DD..E', '.....E', '......'] },
  { world: 'easy', par: 4, rows: ['....BB', '..CCCE', 'AADG.E', 'F.DG.E', 'F..G..', '......'] },
  { world: 'easy', par: 5, rows: ['.C.E..', '.CDEB.', 'AADEB.', '...FF.', '......', '......'] },
  { world: 'easy', par: 6, rows: ['....B.', 'D...B.', 'DAA.F.', '..E.F.', '..ECC.', '......'] },
  { world: 'easy', par: 6, rows: ['.CCCD.', 'FFFBD.', 'AA.BD.', '...HH.', '.GGG..', '...EE.'] },
  { world: 'easy', par: 7, rows: ['..B...', '..BFFF', '.AAE.G', '...E.G', '...E.C', '..DD.C'] },
  { world: 'easy', par: 8, rows: ['..HEE.', '..HBBD', '.AACFD', '...CF.', '....G.', '....G.'] },
  { world: 'easy', par: 9, rows: ['..D...', '..DFF.', 'AADG..', '...G.C', 'EBBG.C', 'E.....'] },
  { world: 'easy', par: 9, rows: ['....FF', 'B....C', 'BAA..C', 'BEEE.C', 'HHDGGG', '..D...'] },
  { world: 'easy', par: 10, rows: ['.....B', 'F..CGB', 'FAACGB', '..HD..', '..HDEE', '......'] },
  { world: 'mid', par: 6, rows: ['.KHH..', '.KDJJI', 'AAD.EI', 'FCCCE.', 'FG.BB.', 'FG....'] },
  { world: 'mid', par: 7, rows: ['C.GGBB', 'C.KKFF', 'AA..IJ', 'HDD.IJ', 'H....E', 'H....E'] },
  { world: 'mid', par: 8, rows: ['...DKK', 'JJ.DFG', '.BAAFG', 'HB.EE.', 'HB..CI', '....CI'] },
  { world: 'mid', par: 8, rows: ['F.IKK.', 'F.IC.D', 'FAAC.D', '.BJJGG', '.B....', '.BHHEE'] },
  { world: 'mid', par: 9, rows: ['...BFF', '...BGG', '..AAJD', '.EEEJD', '.CCCIH', '....IH'] },
  { world: 'mid', par: 10, rows: ['.....G', 'H.EEEG', 'H.AACG', 'HIIDC.', 'JJBD..', '..BDFF'] },
  { world: 'mid', par: 11, rows: ['.BHH..', '.B.DFE', 'AA.DFE', 'IIID..', 'G.....', 'GCCC..'] },
  { world: 'mid', par: 11, rows: ['.BBBF.', '...EFK', '.AAECK', '..HJC.', '..HJDD', '.IIGG.'] },
  { world: 'mid', par: 12, rows: ['....E.', 'B...EF', 'B.AAEF', 'C..DHH', 'CGGDII', '.KKJJ.'] },
  { world: 'mid', par: 13, rows: ['......', 'GD..BE', 'GDAABE', '.JCCBE', '.JIH..', '.JIHFF'] },
  { world: 'mid', par: 14, rows: ['C.DBBB', 'C.DII.', 'CAAFKE', '.HHFKE', '...G..', '...GJJ'] },
  { world: 'mid', par: 14, rows: ['D..E..', 'D..E.H', 'AA.ECH', '....C.', '.GBBC.', '.GFF..'] },
  { world: 'mid', par: 15, rows: ['...BJJ', 'CCCB.E', 'I.AA.E', 'IKKHHE', 'FFD...', '..DGGG'] },
  { world: 'mid', par: 16, rows: ['I..D..', 'I.JDBE', 'AAJHBE', 'KK.H.F', '.GCC.F', '.G....'] },
  { world: 'hard', par: 11, rows: ['..G...', '..GJ.H', 'AABJ.H', '..B.FF', 'CCC..D', 'EEII.D'] },
  { world: 'hard', par: 12, rows: ['..FF..', 'HH.IJ.', 'AA.IJ.', 'DDDI..', 'ECCC..', 'EBBBGG'] },
  { world: 'hard', par: 13, rows: ['.DD.I.', 'C...IF', 'CAABIF', '..GB..', 'J.GBHH', 'JEEE..'] },
  { world: 'hard', par: 14, rows: ['EEE...', 'FFBBBD', 'LAA.ID', 'LGGKID', '..CKJJ', '..CHHH'] },
  { world: 'hard', par: 15, rows: ['...EE.', 'FF..GD', 'AA..GD', 'KKKBBD', 'HJJIII', 'H..CCC'] },
  { world: 'hard', par: 16, rows: ['DDDJ.F', '.EEJ.F', 'AAI..B', 'G.I..B', 'GCCC.B', '...HHH'] },
  { world: 'hard', par: 17, rows: ['JJEEF.', 'BB.LFC', 'AA.LIC', 'GDDDI.', 'G.....', 'G.KKHH'] },
  { world: 'hard', par: 17, rows: ['F.KKB.', 'F.GGB.', 'AAHEB.', '..HEJJ', 'DDDE.I', '...CCI'] },
  { world: 'hard', par: 18, rows: ['.IIGGG', '...BJJ', 'AA.B.L', 'HKDD.L', 'HK..EE', 'HCCCFF'] },
  { world: 'hard', par: 20, rows: ['I.CDDD', 'I.CHBB', 'GAAHMK', 'GL..MK', '.LEEEJ', '.FF..J'] },
  { world: 'hard', par: 21, rows: ['..FIII', 'DDF.B.', 'HAA.B.', 'HJJ...', 'GGEEE.', 'CC....'] },
  { world: 'hard', par: 21, rows: ['.DDIIC', '..HL.C', 'AAHL.B', 'FFJKKB', 'E.J.GG', 'E.....'] },
  { world: 'hard', par: 22, rows: ['J.HHEE', 'J.KKKC', 'AA..MC', 'FFGGMC', 'LLLI..', 'DD.IBB'] },
  { world: 'expert', par: 16, rows: ['JJBBBI', '.GG..I', '.AA.HF', 'EEK.HF', 'C.K.H.', 'CDDLL.'] },
  { world: 'expert', par: 18, rows: ['MMF..B', 'EEF..B', 'HJAA.B', 'HJ.CLL', 'IIICDD', '..GGKK'] },
  { world: 'expert', par: 20, rows: ['.JJLL.', '.CCBNN', 'AAHB..', 'IDHBEE', 'IDKKGM', '.FF.GM'] },
  { world: 'expert', par: 22, rows: ['EIIIMM', 'E.FGGG', 'AAF...', 'LBBKKC', 'LHHH.C', 'JJJDDC'] },
  { world: 'expert', par: 24, rows: ['.JKKCM', '.JFLCM', 'AAFL..', 'D.FBBB', 'DGGH..', 'EE.HII'] },
  { world: 'expert', par: 25, rows: ['..KGGG', 'H.KBII', 'HAABJE', '.L..JE', 'CLMMJE', 'CFFDD.'] },
  { world: 'expert', par: 26, rows: ['.KK.LL', '.BBGGJ', '.AA.CJ', '.IHHCJ', '.IMFDD', 'EEMF..'] },
  { world: 'expert', par: 27, rows: ['DGG.J.', 'DEE.JM', 'AAB..M', 'HHB..L', 'CCCKKL', 'FFFII.'] },
  { world: 'expert', par: 27, rows: ['LLIIKN', 'FBBHKN', 'FAAHDJ', 'GGMHDJ', '.EM...', '.ECCC.'] },
  { world: 'expert', par: 27, rows: ['MM....', 'DK.CCI', 'DKAABI', 'EGNNBI', 'EGHJFF', 'LLHJ..'] },
  { world: 'expert', par: 35, rows: ['DDDLL.', '...KEE', 'AABK.F', 'M.BHHF', 'MJJ.IG', 'NNCCIG'] },
];
