/**
 * 게임 이름표 — 수학 놀이터(19_Mathgame_web) 게임 manifest 에서 2026-10-08 에 뽑아 굳힌 것.
 * 기술 카드의 「이 기술을 쓴 게임」 · 게임 사진(shots/<id>.jpg)에 쓴다. 게임이 늘면 여기에 한 줄.
 */
export const GAME_TITLES: Record<string, string> = {
  abacus: '주판',
  alquerque: '알케르케',
  backgammon: '백개먼',
  balance: '양팔 저울',
  baseten: '수 모형',
  blocks: '쌓기나무',
  bridgit: '다리 잇기',
  buffon: '뷔퐁의 바늘',
  checkpoint: '수학 검문소',
  chess: '수학 체스',
  chopsticks: '젓가락 게임',
  connect4: '사목',
  crownanchor: '왕관과 닻',
  cube: '3×3 큐브',
  dotsboxes: '점과 상자',
  fakecoin: '가짜 동전 찾기',
  farkle: '파클',
  galton: '갈톤 보드',
  geoboard: '지오보드',
  gomoku: '수학 오목',
  gonu: '고누',
  hanoi: '하노이의 탑',
  havannah: '하반나',
  hex: '헥스',
  hexapawn: '헥사폰',
  icestar: '얼음 별 밀기',
  liarsdice: '거짓말쟁이의 주사위',
  manisan: '강화 마니산의 비밀',
  midnight: '자정',
  mirrorlab: '햇빛 거울 보물 동굴',
  morpion: '모르피온 솔리테어',
  morris: '아홉 남자의 모리스',
  nim: '님 게임',
  notakto: '노탁토',
  numbaseball: '숫자 야구',
  onestroke: '스케치북 한붓그리기',
  onyx: '오닉스',
  parking: '빵빵 주차장 탈출',
  pegsolitaire: '페그 솔리테어',
  picaria: '피카리아',
  pig: '피그',
  pixelart: '픽셀 그림 공방',
  polyomino: '폴리오미노',
  probability: '주사위·동전 실험실',
  puzzle15: '수학 15퍼즐',
  pythagoras: '피타고라스 물 실험',
  queens: '공주 정원',
  rivercross: '강 건너기',
  sandae: '산대',
  seven: 'SEVEN',
  shannon: '섀넌 스위칭',
  simpei: '심페이',
  sleepytown: '잠꾸러기 버섯 마을',
  sokoban: '꼬마 창고지기',
  solids: '입체도형 관찰',
  soma: '소마 큐브',
  stock: '주식 투자 게임',
  suika: '과일 합치기',
  suika3d: '3D 과일 합치기',
  surakarta: '수라카르타',
  tangram: '탱그램',
  teeko: '티코',
  tictactoe: '수학 틱택토',
  toybox: '곰돌이 장난감 상자',
  waterjug: '물통 나누기',
  waterway: '물길 잇기 꽃밭',
  yahtzee: '요트 다이스',
};
